name: flutter_tree_sitter_editor
description: "A Flutter editor using tree-sitter to provide syntax highlighting and syntactic analysis."
version: 0.0.1
homepage: https://github.com/qiuxiang/flutter_tree_sitter_editor
repository: https://github.com/qiuxiang/flutter_tree_sitter_editor

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  ffi: ^2.1.2
  flutter:
    sdk: flutter
  flutter_tree_sitter: ^0.0.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
