name: flutter_tree_sitter_editor
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/qiuxiang/flutter_tree_sitter_editor

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  ffi: ^2.1.2
  flutter:
    sdk: flutter
  flutter_tree_sitter:
    path: ../flutter-tree-sitter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
